# This is a basic workflow to help you get started with Actions

name: Introspect

# Controls when the action will run.
on:
  schedule:
    - cron: "0 2 * * 1-5"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get ENV variables
      - run: |
          touch .env
          echo SHOP_HANDLE =${{ secrets.SHOP_HANDLE }} >> .env
          echo API_VERSION =${{ secrets.API_VERSION }} >> .env
          echo API_KEY =${{ secrets.API_KEY }} >> .env
      - name: Install dependencies
      - run: npm install
      - name: Introspect the API
      - run: npm run introspect
      - name: Move files to output # Move the generated files into output folder
        run: |
          mkdir -p output
          yes| cp -rf ${{ secrets.API_VERSION }}.gql ./output/
      - name: Commit files # commit the output folder
        run: |
          git config --local user.email "bot@example.com"
          git config --local user.name "Bot"
          git add ./output
          git commit -m "Update introspection file"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
